Week1/bohye
juhwanHeo/study-react pull request #12
Opened 2024-08-21 03:45 UTC by bobo-h

Week1 과제 1,2,3

2024-08-23 00:48 UTC, juwonlee-dev requested changes

2024-08-23 00:48 UTC, juwonlee-dev commented on bohye/board-project/.gitignore
> +# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.
과제와 관련된 파일만 수정하여 올려주시길 바랍니다.   
해당 파일들은 본 과제와는 아무런 연관이 없습니다.

2024-08-23 00:49 UTC, juwonlee-dev commented
구성한 화면을 캡쳐하여 PR 본문에 첨부하면 좋을 것 같습니다.

2024-08-28 01:25 UTC, bobo-h commented
> 구성한 화면을 캡쳐하여 PR 본문에 첨부하면 좋을 것 같습니다. 다음부터는 커밋 메시지에 보다 구체적인 작업내용을 작성하는 것이 좋을 것 같습니다.

구성화면 캡쳐본 첨부하여 수정하였습니다.

2024-08-29 00:36 UTC, juhwanHeo requested changes
api fuction의 결과 값으로 state를 수정하는게 좋을거 같습니다.

api function은 api call만 하고,
그 결과 값을 받아 state를 수정하는게 확장성에 용이할 것으로 보입니다.

2024-08-29 00:36 UTC, juhwanHeo commented on bohye/board-project/src/App.js
> +        setItems(data);
`fetchData ` Function 은 api에서 data만 가져오고,
setItems는 fetchData에 결과 값으로 수정하는 것이 좋을 것 같습니다.

api 함수는 api call만 하고, 그 결과 값으로 state를 조작하는게 좋을 것 같습니다.

feat

```js
fetchData().then((response) => setItems(response))
```

or

```js
const data = await fetchData();
setItems(data)
```

2024-08-30 12:58 UTC, juwonlee-dev requested changes

2024-08-30 12:58 UTC, juwonlee-dev commented on bohye/board-project/src/components/Board.js
> +        <BoardItem key={index + 1} item={item} index={index + 1} />
과제1에서 언급된 **BoardItem을 렌더링하기 위한 배열이 전달되지 않았을 때**에 대한 조건이 구현되어있지 않습니다.  
items라는 변수로 배열을 받아오고 있으므로, 배열이 비어있을 떄에 대한 예외처리를 해야합니다.

2024-08-30 12:58 UTC, juwonlee-dev commented on bohye/board-project/src/App.js
> +        setItems(data);
이러한 코드는 재사용성을 높이고, 변경사항이 발생했을 때 유연하게 대응할 수 있도록 합니다.  
함수를 작성할 때에는 구현하고자 하는 바를 적절하게 분리하여 설계해야합니다.

2024-09-26 00:37 UTC, juwonlee-dev approved these changes

2024-09-26 08:49 UTC, juhwanHeo commented on bohye/board-project/src/App.js
> +    return data;
data 변수를 다음 코드에서 사용하지 않으므로 다음과 같이 수정하면 좋을 것 같습니다.
```suggestion
    return await response.json();
```

2024-09-28 03:46 UTC, juhwanHeo approved these changes

2024-09-28 03:46 UTC, merged