Feat: Add board-project directory
juhwanHeo/study-react pull request #13
Opened 2024-08-28 15:49 UTC by Mik-WJ

과제 1, 2)
<img width="341" alt="image" src="https://github.com/user-attachments/assets/6a187c60-f60c-457e-b442-9096ea960424">

과제 3) 

<img width="273" alt="image" src="https://github.com/user-attachments/assets/dfd437a7-ac4b-45f2-9f14-31e7687401f1">

2024-08-29 00:49 UTC, juhwanHeo requested changes
Props와 관련된 수정사항이 있습니다.

2024-08-29 00:49 UTC, juhwanHeo commented on ujin/board-project/src/component/Board.js
> +function Board({ items }) {
BoardItems props에 list를 받는 구조라면 Board의 props는 없어도 될 것 같습니다.

또는

Board props에는 `board`
BoardItems props에는 `Array<board>`
로 받도록 수정하면 좋을 것 같습니다.

(아래 방법이 더 좋아 보입니다,)

2024-08-30 13:19 UTC, juwonlee-dev requested changes

2024-08-30 13:19 UTC, juwonlee-dev commented on ujin/board-project/src/component/Board.js
> +                    console.log(boardItems)
항상 테스트 및 디버깅을 목적으로 작성한 코드는 목적을 달성했다면 지우는 습관을 들여야합니다.   
지워지지 않고 남아있는 디버그 코드는 사이트의 취약점 또는 이를 찾아내기 위해 활용될 수 있는 시스템의 정보를 제공하게됩니다.

2024-08-30 13:19 UTC, juwonlee-dev commented on ujin/board-project/src/component/Menu.js
> +function Logo() {
Menu 컴포넌트는 이번주차 과제와 관련이 없습니다.
과제에 해당하는 내용만 올려주세요.

2024-08-30 13:20 UTC, juwonlee-dev commented on ujin/board-project/src/component/Board.js
> +function Board({ items }) {
Board와 BoardItem 컴포넌트를 작성할 때, 어느 부분을 나누어 설계할지에 대해서 충분히 고민해보시는 것이 좋을 것 같습니다.
작성된 코드는 위에 이야기한 것처럼, 본인 스스로도 그 범위에 혼동이 있는 것으로 보여집니다.

2024-09-26 00:43 UTC, juwonlee-dev approved these changes

2024-09-26 08:51 UTC, juhwanHeo approved these changes

2024-09-26 08:51 UTC, merged