Week2 / CUD / bohye
juhwanHeo/study-react pull request #17
Opened 2024-09-25 03:33 UTC by bobo-h

issue: #15 과제 CUD, 
![Screenshot 2024-09-26 at 15 21 54](https://github.com/user-attachments/assets/4853346f-360c-4a43-9f07-9317a6e85789)

2024-09-28 07:08 UTC, juhwanHeo requested changes
필드 선언과 메소드 선언의 위치를 이동 시켜 주세요.

보통은 
필드 선언, 메소드 선언 순서입니다.

2024-09-28 07:08 UTC, juhwanHeo commented on bohye/board-project/src/App.js
> +  const [createMode, setCreateMode] = useState(false);
변수(상태) 선언 부와 메소드 선언부의 위치를 통일시켜 주는게 좋을 것 같습니다.

현재 
- 변수 선언부
- useEffect
- 변수 선언부
- 메소드 선언부 

변경
- 변수 선언부
- useEffect
- 메소드 선언부

2024-09-28 07:08 UTC, juhwanHeo commented on bohye/board-project/src/components/BoardItem.js
> +  };
변수(상태) 선언 부와 메소드 선언부의 위치를 통일시켜 주는게 좋을 것 같습니다.

현재 
- 변수 선언부
- 메소드 선언부 
- 변수 선언부

변경
- 변수 선언부
- 메소드 선언부

2024-09-28 07:08 UTC, juhwanHeo commented on bohye/board-project/src/components/cud/Update.js
> +  const handleCancelClick = () => {
한 칸 띄워 주시면 좋을 것 같습니다.

2024-09-29 12:32 UTC, juwonlee-dev requested changes

2024-09-29 12:32 UTC, juwonlee-dev commented on bohye/board-project/src/App.js
> +  const [createMode, setCreateMode] = useState(false);
선언부를 정리하는 것은 중요합니다. 해당 프로세스에서 사용하는 변수나 함수에 대해 명시하고 중복선언되거나 불필요하게 선언되어 사용되지 않는 미사용코드가 생기게됩니다.

2024-09-29 12:32 UTC, juwonlee-dev commented on bohye/board-project/src/components/Board.js
>      <div className={classes.main}>
CSS Module로 스타일을 적용하는 것은 좋은 접근이나, 불필요한 부분까지 무분별하게 `classes.클래스명`이 사용되고 있습니다.  
css bind는 조건부 스타일링을 요구하는 부분에서 유용하게 사용하는 기능으로 조건에 따라 클래스를 다르게 부여해야할 경우 사용합니다.  
`{}` 내부의 코드는 자바스크립트로 실행하게됩니다. 따라서 필요한 경우가 아니라면 `className="main"`과 같이 작성하여 렌더링 과정에서 불필요한 코드 실행을 최소화하는 것이 바람직합니다.  
현재 작성하신 대부분의 내용에서는 조건부 스타일링을 적용하는 것이 아니라 단순히 클래스를 지정하는 용도로 사용하고 있으므로 불필요합니다.

2024-09-30 09:19 UTC, bobo-h commented on bohye/board-project/src/components/Board.js
>      <div className={classes.main}>
css bind는 사용하지 않았고 css module을 임포트 하는 과정에서 정의한 이름이 classes입니다. css module을 사용하기 위해선 className={임포트명.클래스명} 으로 사용하도록 배워서 해당 내용으로 코드를 작성한 것인데, 
조건부 스타일링을 사용하는 경우에만 css module을 사용하시라는 말씀이실까요?

2024-09-30 11:11 UTC, juwonlee-dev commented on bohye/board-project/src/components/Board.js
>      <div className={classes.main}>
bind에 대한 내용은 개념을 설명드린 것입니다. bind를 사용했다는 것으로 오해의 소지가 있다면 정정하도록 하겠습니다.

CSS Module을 사용하는 경우는 다음과 같은 케이스가 있습니다. 
1. CSS의 적용 범위를 컴포넌트로 제한하고자 하는 경우(컴포넌트 기반의 스타일링)
2. 클래스명의 간소화(컴포넌트로 범위가 제한되며 해당 컴포넌트마다 고유한 클래스명이 자동으로 부여되어 다른 컴포넌트와 중복되지 않습니다.)
Global CSS를 별도로 관리하고 각 컴포넌트별로 스타일을 적용, 관리하고자 의도했다면 적합한 것 같습니다.

2024-10-11 15:49 UTC, juwonlee-dev approved these changes

2024-10-11 15:49 UTC, merged