WIP) Week2 / Create, Update, Delete / juwonlee
juhwanHeo/study-react pull request #18
Opened 2024-09-25 08:09 UTC by juwonlee-dev

2024-09-28 04:09 UTC, bobo-h approved these changes

2024-09-28 07:23 UTC, juhwanHeo requested changes
하나의 boarditem을 수정하고, 등록 버튼을 클릭하면 이전 입력값이 출력되고, 
저장 버튼 클릭시 빈 값으로 저장되는 현상이 있습니다. 이것도 확인 부탁드립니다.

2024-09-28 07:23 UTC, juhwanHeo commented on juwonlee/board-project/src/components/Form/ItemModal/index.js
> +  const onActionandler = (item) => {
onActionandler의 식별자가 이상합니다.

onActionHandler로 변경해 주세요.

2024-09-28 07:23 UTC, juhwanHeo commented on juwonlee/board-project/src/components/Form/ItemModal/index.js
> +          <div className='add-btn' onClick={() => onActionandler(item)}>{ actionText || '확인' }</div>
onActionandler의 식별자가 이상합니다.

onActionHandler로 변경해 주세요.

2024-09-28 07:23 UTC, juhwanHeo commented on juwonlee/board-project/src/components/Form/Input/index.js
> +
불필요한 useEffect 로 보입니다.
확인부탁드립니다.

2024-09-29 11:38 UTC, juwonlee-dev commented on juwonlee/board-project/src/components/Form/Input/index.js
> +
Input 컴포넌트로 value를 props로 제공하는 경우, useState에 그 값을 업데이트합니다.  
이때, useEffect를 사용하지 않고 ```setInputValue(value || '')```를 호출하도록 렌더 함수에 작성하게 되면 과도하게 많은 리렌더링이 발생하여 오류가 발생합니다.  
따라서 props로 전달되는 value에 변경이 일어날 경우에만 전달받은 value를 input에 기본값으로 지정시킬 수 있도록 useEffect를 사용했습니다.

2024-10-11 15:51 UTC, juhwanHeo approved these changes

2024-10-11 15:51 UTC, merged