Week2/ CUD / juhwan
juhwanHeo/study-react pull request #19
Opened 2024-09-27 02:54 UTC by juhwanHeo

2024-09-28 04:32 UTC, bobo-h commented on juhwan/board-project/src/components/board/cud/Create.tsx
> +        <div>creator: <input id={"edit-board-creator"} value={creator} onChange={(e) => setCreator(e.target.value)}/></div>
빈값으로는 글 작성이 되지 않게 처리해주시는 게 좋을 것 같습니다

2024-09-29 12:09 UTC, juwonlee-dev requested changes

2024-09-29 12:09 UTC, juwonlee-dev commented on juhwan/board-project/src/App.tsx
> +          boardItemsProps?.items.length === 0
boardItemsProps에 `{items: Array}` 형태의 객체를 저장하여 사용하고 있는 것으로 이해되는데, API로부터 받아온 결과값에 대한 예외처리가 부족해보입니다.  
boardItemsProps에 items가 존재하지 않거나 boardItemsProps 자체가 null인 경우에 대해서는 처리가 되나 boardItemsProps.items에 배열이 아닌 다른 형태의 값이 들어가는 경우에 대해 처리해야 합니다.  
본 과제에서 사용한 API에서는 여러 데이터를 배열로 제공하고 있으니 useEffect에서 setBoardItemProps를 사용하여 저장할 때 `setBoardItemProps({items: res || []})`와 같이 처리를 해주는 것이 좋을 것 같습니다.

2024-09-29 12:09 UTC, juwonlee-dev commented on juhwan/board-project/src/App.tsx
> +          boardItemsProps?.items.length === 0
추가로, useState에서 boardItemsProps로 명명하였으니 setter 역시 setBoardItemsProps로 명칭을 통일시켜주는 것이 좋을 것 같습니다.

2024-09-29 12:09 UTC, juwonlee-dev commented on juhwan/board-project/src/components/board/cud/Update.tsx
> +
두줄을 개행하여 구분하지 않아도 될 것 같습니다.  
한줄만 개행하여도 구분함에 있어서 어려움이 없어보입니다.

2024-09-29 12:10 UTC, juwonlee-dev commented on juhwan/board-project/src/components/board/cud/Create.tsx
> +        <div>creator: <input id={"edit-board-creator"} value={creator} onChange={(e) => setCreator(e.target.value)}/></div>
@bobo-h 
수정을 희망하는 부분이 있으신 경우에는, Approve가 아니라 Change Request로 리뷰를 남겨주셔야 합니다.

2024-10-11 07:15 UTC, bobo-h approved these changes

2024-10-11 15:50 UTC, juwonlee-dev approved these changes

2024-10-11 15:50 UTC, merged