Week1 / Component & Props , Event & State / yiseoul
juhwanHeo/study-react pull request #32
Opened 2024-10-26 20:13 UTC by LSHgy

## Issue #8

### 과제 결과
![image](https://github.com/user-attachments/assets/9afef813-a5d8-47b6-8dfc-06a25c9bf112)

2024-10-27 08:45 UTC, bobo-h requested changes
전체적인 인덴트 수정 바랍니다.

2024-10-27 08:45 UTC, bobo-h commented on yiseoul/board-project/src/components/board/BoardHeader.js
> +}
인덴트 확인 바랍니다

2024-10-27 08:45 UTC, bobo-h commented on yiseoul/board-project/src/components/board/BoardItem.js
> +}
인덴트 확인 바랍니다,

2024-10-27 08:45 UTC, bobo-h commented on yiseoul/board-project/src/components/board/BoardItem.js
> +					<div className="board-row" key={index}>
key값으로 index를 사용하시는 것에 대해 찾아보시면 좋을 것 같습니다.

2024-10-27 08:45 UTC, bobo-h commented on yiseoul/board-project/src/components/board/Board.js
> +	);
인덴트 확인 바랍니다.

2024-10-27 08:45 UTC, bobo-h commented on yiseoul/board-project/src/components/board/Board.js
> +}
인덴트 확인 바랍니다.

2024-11-12 04:30 UTC, bobo-h approved these changes

2024-11-14 03:17 UTC, juwonlee-dev approved these changes

2024-11-16 07:42 UTC, merged