Week4 / 폼, State 끌어올리기 / ujin
juhwanHeo/study-react pull request #37
Opened 2024-11-17 16:20 UTC by Mik-WJ

#24 

Arcodion and Panel components )

<img width="646" alt="image" src="https://github.com/user-attachments/assets/40b00312-8b45-412e-a97c-40642e7f6405">

2024-11-23 04:50 UTC, juhwanHeo requested changes
이전 과제 컴포넌트를 롤백 후 요청해 주세요!

2024-11-23 04:50 UTC, juhwanHeo commented on ujin/board-project/src/component/priority/And.js
이전 과제의 컴포넌트를 삭제할 필요는 없습니다.

호출 하는 부분만 삭제, 주석 처리해주시면 됩니다.

2024-11-23 04:50 UTC, juhwanHeo commented on ujin/board-project/src/component/priority/OR.js
이전 과제의 컴포넌트를 삭제할 필요는 없습니다.

호출 하는 부분만 삭제, 주석 처리해주시면 됩니다.

2024-11-28 12:50 UTC, juwonlee-dev requested changes
파일 경로를 올바르게 통일해주세요.   
(component -> components)

2024-12-01 09:54 UTC, juhwanHeo approved these changes

2024-12-22 14:33 UTC, merged