Week 5 / 합성,상속 & React로 생각하기 / ujin
juhwanHeo/study-react pull request #40
Opened 2024-11-28 15:07 UTC by Mik-WJ

Issue: #33 

과제 1) 

<img width="456" alt="스크린샷 2024-11-29 오전 12 06 24" src="https://github.com/user-attachments/assets/f13528bb-87b9-4b01-8f26-5093be3ff1a1">

2024-11-29 07:46 UTC, bobo-h requested changes
1. 수정 시 취소 버튼을 누르면 테이블에 제목 값이 사라진 상태가 됩니다.
2. 빈 값으로 검색 버튼을 눌렀을 때의 반응도 있으면 좋을 것 같습니다.
3. 검색어를 띄어쓰기 값이나 임의의 값을 넣고 찾기 버튼을 누를 때마다 id값이 변경됩니다. id값을 key값으로 보이게 하셨기에 의도하신 것이라면 이유가 궁금합니다.

2024-12-01 10:03 UTC, juhwanHeo requested changes
불필요한 개행이 몇개 보입니다.
수정부탁드립니다.

2024-12-01 10:03 UTC, juhwanHeo commented on ujin/board-project/src/components/Board/Search.js
> +
불필요한 개행문자 인것 같습니다.

2024-12-01 10:03 UTC, juhwanHeo commented on ujin/board-project/src/components/Board/Search.js
> +
불필요한 개행문자 인거 같습니다.

2024-12-21 07:24 UTC, Mik-WJ commented
> 1. 수정 시 취소 버튼을 누르면 테이블에 제목 값이 사라진 상태가 됩니다.
> 2. id값을 key값으로 설정하셨기에 state가 변화될때 마다 id값이 변경이 되는 것이 보이는데 의도하신 것이라면 이유가 궁금합니다.

1번은 수정 완료 했고 
2번은 사실 따로 의도는 없고 변화를 확실히 확인하기 위해 했습니다.

2024-12-21 12:57 UTC, juhwanHeo approved these changes

2024-12-22 09:48 UTC, bobo-h approved these changes

2024-12-22 14:33 UTC, juwonlee-dev approved these changes

2024-12-22 14:33 UTC, merged