Week 5 / 합성,상속 & React로 생각하기 / bohye
juhwanHeo/study-react pull request #41
Opened 2024-11-29 04:14 UTC by bobo-h

issue: #33 
![스크린샷 2024-11-29 130942](https://github.com/user-attachments/assets/fd6a5857-f401-44b5-a924-09f588f915a8)

2024-12-01 10:16 UTC, juhwanHeo requested changes
api 호출부에 수정사항이 있습니다.

2024-12-01 10:16 UTC, juhwanHeo commented on bohye/board-project/src/components/Board.js
> +        : "http://heojh.iptime.org:8003/board";
삼항연산자를 사용하지 않고, 
하나의 문자열로 해결 가능해 보입니다.

2024-12-01 10:16 UTC, juhwanHeo commented on bohye/board-project/src/components/Board.js
> +      setItems(dataWithKeys);
api 호출 함수와 response list를 조작하는 부분을 다른 함수로 나누면 어떨까요?

2024-12-26 08:55 UTC, bobo-h commented on bohye/board-project/src/components/Board.js
> +        : "http://heojh.iptime.org:8003/board";
axios 사용해서 하나의 문자열로 해결하였습니다.

2024-12-26 08:56 UTC, bobo-h commented on bohye/board-project/src/components/Board.js
> +      setItems(dataWithKeys);
key값을 id값으로 변경하여 리스트를 매핑하는 함수를 없애는 것으로 해결하였습니다

2025-01-02 09:30 UTC, juhwanHeo approved these changes

2025-01-02 09:30 UTC, juhwanHeo commented on bohye/board-project/src/components/Board.js
> +      console.log("API Response:", data);
해당 부분은 지워도 될것 같습니다.

2025-01-03 06:54 UTC, juwonlee-dev approved these changes

2025-01-03 06:54 UTC, merged