Week 6 / Reducer, Context / ujin
juhwanHeo/study-react pull request #48
Opened 2024-12-28 17:47 UTC by Mik-WJ

issue : #43

2025-01-02 09:34 UTC, juhwanHeo requested changes
수정사항 하나가 있습니다.

2025-01-02 09:34 UTC, juhwanHeo commented on ujin/board-project/src/components/Board/Board.js
> +                    initData: res
indent가 이상합니다.

2025-01-05 07:34 UTC, juhwanHeo requested changes
불필요한 공백이 있습니다.

2025-01-05 07:34 UTC, juhwanHeo commented on ujin/board-project/src/components/Board/Board.js
> +
불필요한 공백입니다.

2025-01-27 19:39 UTC, juwonlee-dev approved these changes

2025-03-16 06:20 UTC, merged