Week0/bohye
juhwanHeo/study-react pull request #5
Opened 2024-07-14 14:55 UTC by bobo-h

2024-07-16 14:17 UTC, juhwanHeo requested changes
수정하면 좋을 것 같은 것이 있습니다.

1. `Hello` Component에 `Menu` Component를 호출한 것
  - 만약 App.js 에서 하나의 Component만 호출하고 싶은 경우에는 메인을 뜻하는 Component를 따로 만들어서 호출 하는 것이 좋아 보입니다. 
  - Hello Component는 Hello World만 출력하는 기능을 가지고 있으므로 다른 기능을 추가하지 않는 것이 좋을 것 같습니다.

2. tag attribute indent 통일

3. Menu Component 재사용성 (필수 사항은 아닙니다. ~한번 수정해 보는 것도 좋을 것 같습니다.~)

2024-07-16 14:17 UTC, juhwanHeo commented on bohye/hello-world/src/components/Hello.js
> +      <Menu />
Hello Component 에서는 `Menu Component`를 호출하지 않는 것이 좋을 것 같습니다.

2024-07-16 14:17 UTC, juhwanHeo commented on bohye/hello-world/src/components/Menu.js
> +      </a>
tag attribute indent는 둘 중 하나로 맞춰주는 것이 좋아보입니다.
```suggestion
      <a
        href="https://www.naver.com/"
        target="_blank"
        rel="noreferrer"
      >
        Naver
      </a>
```

2024-07-16 14:17 UTC, juhwanHeo commented on bohye/hello-world/src/components/Menu.js
> +const Menu = () => {
[ppt의 menu component](https://docs.google.com/presentation/d/1JkJh86h8wX5xOddbw0U1P2yccyjuB5vq8uZdweIIp5Y/edit#slide=id.g27328d0d16a_0_5)는

```js
function 메뉴({제목, 링크}) {
  return (
     <a href={링크}>{제목}</a>
 );
}

export 메뉴;
```
이런식으로 재사용성을 높였습니다.
물론 이 부분은, component의 props 부분에서 배울 내용이라 추가 작업을 안 하셔도 되지만, 한번 도전해보는 것도 좋을 것 같습니다.

2024-07-16 17:49 UTC, juwonlee-dev requested changes

2024-07-16 17:49 UTC, juwonlee-dev commented on bohye/hello-world/src/components/Hello.js
> +      <Menu />
위와 같은 구성은 Menu 컴포넌트가 Hello 컴포넌트 하위에 종속되는 구성으로 Hello 컴포넌트는 반드시 Menu 컴포넌트와 같이 사용되게 됩니다. 컴포넌트간 불필요한 의존성은 재사용성을 해칠 수 있습니다.

2024-07-16 17:49 UTC, juwonlee-dev commented on bohye/hello-world/src/components/Menu.js
> +      </a>
code style을 일관되게 작성하는 것은 프로그램 실행에는 영향을 주지 않으나, 매우 중요한 일입니다.   
작성된 코드의 일관성이 보장되지 않는다면, 동일한 기능에 대해서 다양한 예외를 발생시키게 되며 유지보수에 어려움을 주게 됩니다.

2024-07-18 14:15 UTC, juhwanHeo requested changes
메뉴 컴포넌트에 대한 수정 사항이 있습니다.

2024-07-18 14:15 UTC, juhwanHeo commented on bohye/hello-world/src/components/Menu.js
> +    </>
Menu Components props를 `Array<object>` 타입으로 받을 시 re-rendering 에 대한 문제가 생길 수 있습니다.
https://github.com/juhwanHeo/study-react/blob/63ac3d78af08c4483ea561b7b240cdf70426e5af/bohye/hello-world/src/App.js#L5-L8
예를 들어 App.js에서
```js
site[0].title = "네이버";
```
라는 수정 로직이 들어간다고 하면 naver와 , google 메뉴 2개가 re-rendering이 됩니다.
Menu의 Props를 `Array<object>` -->  `object` 타입으로 변경하면 좋을것 같습니다.

2024-07-18 23:09 UTC, juwonlee-dev requested changes

2024-07-18 23:09 UTC, juwonlee-dev commented on bohye/hello-world/src/components/Hello.js
> +import React from "react";
필요한 import인가요?

2024-07-18 23:09 UTC, juwonlee-dev commented on bohye/hello-world/src/components/Menu.js
> +import React from "react";
필요한 import인가요?

2024-07-19 01:24 UTC, juhwanHeo approved these changes
생각해 보니 해당 내용은 props 챕터의 내용이므로 
props 챕터 이후에 도전해 보셔도 됩니다.

2024-07-19 05:55 UTC, juwonlee-dev approved these changes

2024-07-20 04:31 UTC, juhwanHeo approved these changes

2024-07-20 04:37 UTC, merged